from os import environ

DEBUG = False
SECRET_KEY = environ.get('SECRET_KEY')

SQLALCHEMY_DATABASE_URI = environ.get('DATABASE_URL')
SQLALCHEMY_TRACK_MODIFICATIONS = True

GOOGLE_MAPS_KEY = environ.get('GOOGLE_MAPS_KEY')
