"""empty message

Revision ID: 2d94593a40ee
Revises: 192f3413f418
Create Date: 2017-12-01 01:29:46.293343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d94593a40ee'
down_revision = '192f3413f418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('ATM', sa.Column('address', sa.String(), nullable=True))
    op.add_column('ATM', sa.Column('name', sa.String(), nullable=True))
    op.add_column('ATM', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('ATM', sa.Column('photo_reference', sa.String(), nullable=True))
    op.drop_index('idx_ATM_location', table_name='ATM')
    op.create_unique_constraint(None, 'ATM', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ATM', type_='unique')
    op.create_index('idx_ATM_location', 'ATM', ['location'], unique=False)
    op.drop_column('ATM', 'photo_reference')
    op.drop_column('ATM', 'photo')
    op.drop_column('ATM', 'name')
    op.drop_column('ATM', 'address')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
